list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_chart_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_chat_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_clock_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_game_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_joystick_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_led_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_leds_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_panel_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_sensors_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_stat_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/ui_toggle_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/desktop_ui_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/desktop_ui.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_body_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_clock_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_label_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_small_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_symbols_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_title_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/font_value_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/logo_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/main_screen_gen.c)